import { useI18n, type Locale } from "../lib/i18n";

const enRecovery = {
"recoveryCenter.eyebrow": "Offline recovery",
"recoveryCenter.title": "Recovery Center",
"recoveryCenter.safeModeBody": "Safe Mode is active. Only credential-free recovery controls are available; models, tools, plugins, hooks, and prior sessions are not loaded.",
"recoveryCenter.crashLoopBody": "Repeated incomplete starts were detected. Review the evidence before returning to a normal launch.",
"recoveryCenter.healthyBody": "No actionable recovery issue is present. The evidence below is read-only until you explicitly choose an operation.",
"recoveryCenter.attentionBody": "Recovery evidence needs attention. Review the findings and choose only the operation that matches the failure.",
"recoveryCenter.refresh": "Refresh",
"recoveryCenter.close": "Back to workspace",
"recoveryCenter.credentialFree": "This view does not load API keys, user configuration, model providers, MCP, plugins, hooks, or the Agent runtime.",
"recoveryCenter.loading": "Inspecting recovery evidence…",
"recoveryCenter.statusOverview": "Recovery status overview",
"recoveryCenter.startup": "Startup ledger",
"recoveryCenter.configuration": "Configuration",
"recoveryCenter.releaseUnit": "Installed release",
"recoveryCenter.extensions": "Extensions",
"recoveryCenter.notRecorded": "Not recorded",
"recoveryCenter.failures": "{count} incomplete start(s) in the bounded window",
"recoveryCenter.configValid": "{valid} of {total} checks safe",
"recoveryCenter.snapshots": "{count} verified snapshot(s)",
"recoveryCenter.noSnapshots": "No verified snapshots",
"recoveryCenter.updatePending": "{version} is probationary",
"recoveryCenter.noPendingUpdate": "No pending update",
"recoveryCenter.binaries": "{count} release component(s) inspected",
"recoveryCenter.noBinaryEvidence": "No installed binary evidence",
"recoveryCenter.pluginsEnabled": "{count} plugin(s) enabled",
"recoveryCenter.pluginsDisabled": "{count} plugin(s) disabled",
"recoveryCenter.storeUnreadable": "State store is unreadable",
"recoveryCenter.findings": "Findings",
"recoveryCenter.findingsHint": "Evidence is ordered by severity and does not trigger changes on its own.",
"recoveryCenter.noFindings": "No recovery findings",
"recoveryCenter.actions": "Recovery operations",
"recoveryCenter.actionsHint": "Every operation is explicit, bounded, revalidated, and followed by a fresh inspection.",
"recoveryCenter.repairConfig": "Quarantine invalid configuration",
"recoveryCenter.repairConfigBody": "Move only the selected invalid TOML aside. Global configuration restores the latest verified snapshot when one exists.",
"recoveryCenter.repairGlobal": "Repair global",
"recoveryCenter.repairProject": "Repair project",
"recoveryCenter.repair": "Repair",
"recoveryCenter.rollbackUpdate": "Roll back installed release",
"recoveryCenter.rollbackUpdateBody": "Restore the complete previous release unit only when the observed transaction identity and every backup hash still match.",
"recoveryCenter.rollback": "Roll back",
"recoveryCenter.restoreSnapshot": "Restore configuration snapshot",
"recoveryCenter.restoreSnapshotBody": "Replace the global configuration with one verified snapshot and preserve an undo transaction.",
"recoveryCenter.snapshot": "Verified snapshot",
"recoveryCenter.restore": "Restore",
"recoveryCenter.undoRepair": "Undo last repair",
"recoveryCenter.undoRepairBody": "Undo only the exact recovery transaction currently shown in this report.",
"recoveryCenter.undo": "Undo",
"recoveryCenter.disablePlugins": "Disable all plugins",
"recoveryCenter.disablePluginsBody": "Quarantine extension execution without deleting installed packages or reading their credentials.",
"recoveryCenter.disable": "Disable plugins",
"recoveryCenter.pluginsCanReenable": "Packages remain installed and can be re-enabled later after review.",
"recoveryCenter.rebuildState": "Rebuild desktop state",
"recoveryCenter.rebuildStateBody": "Quarantine derived tab, project, window, or zoom state so Desktop can rebuild it from canonical data.",
"recoveryCenter.rebuildTarget": "Derived state",
"recoveryCenter.rebuildAll": "All derived state",
"recoveryCenter.rebuildTabs": "Tabs",
"recoveryCenter.rebuildProjects": "Projects",
"recoveryCenter.rebuildWindow": "Window placement",
"recoveryCenter.rebuildZoom": "Zoom",
"recoveryCenter.rebuild": "Rebuild",
"recoveryCenter.working": "Working…",
"recoveryCenter.confirmRepairTitle": "Repair configuration?",
"recoveryCenter.confirmRepairGlobal": "Quarantine the invalid global configuration and restore a verified snapshot when available?",
"recoveryCenter.confirmRepairProject": "Quarantine the invalid project configuration for the current workspace?",
"recoveryCenter.confirmRollbackTitle": "Roll back this release?",
"recoveryCenter.confirmRollback": "Restore the complete release that preceded {version}?",
"recoveryCenter.confirmRestoreTitle": "Restore this snapshot?",
"recoveryCenter.confirmRestore": "Replace the global configuration with the selected verified snapshot?",
"recoveryCenter.confirmUndoTitle": "Undo the last repair?",
"recoveryCenter.confirmUndo": "Restore the state that existed immediately before the displayed repair transaction?",
"recoveryCenter.confirmDisableTitle": "Disable all plugins?",
"recoveryCenter.confirmDisable": "Disable every currently enabled plugin before the next normal launch?",
"recoveryCenter.confirmRebuildTitle": "Rebuild desktop state?",
"recoveryCenter.confirmRebuild": "Quarantine the selected derived state and let Desktop recreate it?",
"recoveryCenter.reversibleHint": "The previous file is quarantined and recorded in an undo transaction.",
"recoveryCenter.rebuildQuarantineHint": "Existing files are renamed, not deleted.",
"recoveryCenter.evidenceDetails": "Technical evidence",
"recoveryCenter.binariesTitle": "Release components",
"recoveryCenter.sessionsTitle": "Session stores",
"recoveryCenter.configTitle": "Configuration checks",
"recoveryCenter.ok": "OK",
"recoveryCenter.unavailable": "Unavailable",
"recoveryCenter.files": "{count} file(s)",
"recoveryCenter.missing": "Missing",
"recoveryCenter.invalid": "Invalid",
"recoveryCenter.generatedAt": "Evidence generated at {time}",
"recoveryCenter.actionChanged": "Recovery operation completed and evidence was refreshed.",
"recoveryCenter.actionNoChange": "The operation completed; no matching state required a change.",
"recoveryCenter.finding.startupStateInvalid": "Startup ledger is unreadable",
"recoveryCenter.finding.crashLoop": "Repeated incomplete startup",
"recoveryCenter.finding.configInvalid": "Configuration is invalid",
"recoveryCenter.finding.snapshotsUnreadable": "Configuration snapshots are unreadable",
"recoveryCenter.finding.repairMetadataInvalid": "Repair transaction metadata is invalid",
"recoveryCenter.finding.updateProbationary": "Installed update is still probationary",
"recoveryCenter.finding.updateMetadataInvalid": "Update transaction metadata is invalid",
"recoveryCenter.finding.pluginsInvalid": "Plugin state is unreadable",
"recoveryCenter.open": "Open Recovery Center",
"recoveryCenter.banner": "Recovery evidence needs attention.",
} as const;

type RecoveryKey = keyof typeof enRecovery;
type RecoveryDictionary = Record<RecoveryKey, string>;

const zhRecovery: RecoveryDictionary = {
"recoveryCenter.eyebrow": "离线恢复",
"recoveryCenter.title": "恢复中心",
"recoveryCenter.safeModeBody": "安全模式已启用。当前只提供不读取凭据的恢复控制；模型、工具、插件、Hook 和旧会话均未加载。",
"recoveryCenter.crashLoopBody": "检测到连续未完成启动。返回正常启动前，请先核对恢复证据。",
"recoveryCenter.healthyBody": "当前没有需要处理的恢复问题。在你明确选择操作前，下方证据均为只读。",
"recoveryCenter.attentionBody": "恢复证据需要关注。请核对问题，只执行与实际故障相符的操作。",
"recoveryCenter.refresh": "刷新",
"recoveryCenter.close": "返回工作区",
"recoveryCenter.credentialFree": "此界面不会加载 API 密钥、用户配置、模型服务商、MCP、插件、Hook 或 Agent 运行时。",
"recoveryCenter.loading": "正在检查恢复证据…",
"recoveryCenter.statusOverview": "恢复状态概览",
"recoveryCenter.startup": "启动账本",
"recoveryCenter.configuration": "配置",
"recoveryCenter.releaseUnit": "已安装版本",
"recoveryCenter.extensions": "扩展",
"recoveryCenter.notRecorded": "尚未记录",
"recoveryCenter.failures": "限定窗口内有 {count} 次未完成启动",
"recoveryCenter.configValid": "{total} 项检查中 {valid} 项安全",
"recoveryCenter.snapshots": "{count} 份已验证快照",
"recoveryCenter.noSnapshots": "没有已验证快照",
"recoveryCenter.updatePending": "{version} 仍在观察期",
"recoveryCenter.noPendingUpdate": "没有待确认更新",
"recoveryCenter.binaries": "已检查 {count} 个发布组件",
"recoveryCenter.noBinaryEvidence": "没有已安装二进制证据",
"recoveryCenter.pluginsEnabled": "已启用 {count} 个插件",
"recoveryCenter.pluginsDisabled": "已禁用 {count} 个插件",
"recoveryCenter.storeUnreadable": "状态存储不可读",
"recoveryCenter.findings": "发现的问题",
"recoveryCenter.findingsHint": "证据按严重程度排序，不会自行触发任何改动。",
"recoveryCenter.noFindings": "没有恢复问题",
"recoveryCenter.actions": "恢复操作",
"recoveryCenter.actionsHint": "每项操作都需要明确确认、范围受限、执行前复核身份，并在完成后重新检查。",
"recoveryCenter.repairConfig": "隔离无效配置",
"recoveryCenter.repairConfigBody": "只移走所选的无效 TOML；若存在已验证快照，全局配置会自动恢复最新一份。",
"recoveryCenter.repairGlobal": "修复全局配置",
"recoveryCenter.repairProject": "修复项目配置",
"recoveryCenter.repair": "修复",
"recoveryCenter.rollbackUpdate": "回滚已安装版本",
"recoveryCenter.rollbackUpdateBody": "只有当前事务身份和所有备份哈希仍完全匹配时，才恢复完整的上一发布单元。",
"recoveryCenter.rollback": "回滚",
"recoveryCenter.restoreSnapshot": "恢复配置快照",
"recoveryCenter.restoreSnapshotBody": "用一份已验证快照替换全局配置，并保留可撤销事务。",
"recoveryCenter.snapshot": "已验证快照",
"recoveryCenter.restore": "恢复",
"recoveryCenter.undoRepair": "撤销上次修复",
"recoveryCenter.undoRepairBody": "只撤销当前报告中显示的精确恢复事务。",
"recoveryCenter.undo": "撤销",
"recoveryCenter.disablePlugins": "禁用全部插件",
"recoveryCenter.disablePluginsBody": "停止扩展执行，但不删除已安装包，也不读取其凭据。",
"recoveryCenter.disable": "禁用插件",
"recoveryCenter.pluginsCanReenable": "插件包仍会保留，完成审查后可再次启用。",
"recoveryCenter.rebuildState": "重建桌面状态",
"recoveryCenter.rebuildStateBody": "隔离标签页、项目、窗口或缩放等派生状态，由 Desktop 根据规范数据重建。",
"recoveryCenter.rebuildTarget": "派生状态",
"recoveryCenter.rebuildAll": "全部派生状态",
"recoveryCenter.rebuildTabs": "标签页",
"recoveryCenter.rebuildProjects": "项目",
"recoveryCenter.rebuildWindow": "窗口位置",
"recoveryCenter.rebuildZoom": "缩放",
"recoveryCenter.rebuild": "重建",
"recoveryCenter.working": "执行中…",
"recoveryCenter.confirmRepairTitle": "修复配置？",
"recoveryCenter.confirmRepairGlobal": "隔离无效全局配置，并在可用时恢复已验证快照？",
"recoveryCenter.confirmRepairProject": "隔离当前工作区的无效项目配置？",
"recoveryCenter.confirmRollbackTitle": "回滚此版本？",
"recoveryCenter.confirmRollback": "恢复安装 {version} 之前的完整发布单元？",
"recoveryCenter.confirmRestoreTitle": "恢复此快照？",
"recoveryCenter.confirmRestore": "用所选已验证快照替换全局配置？",
"recoveryCenter.confirmUndoTitle": "撤销上次修复？",
"recoveryCenter.confirmUndo": "恢复到当前显示的修复事务执行前的状态？",
"recoveryCenter.confirmDisableTitle": "禁用全部插件？",
"recoveryCenter.confirmDisable": "在下次正常启动前禁用所有当前已启用的插件？",
"recoveryCenter.confirmRebuildTitle": "重建桌面状态？",
"recoveryCenter.confirmRebuild": "隔离所选派生状态并让 Desktop 重新创建？",
"recoveryCenter.reversibleHint": "原文件会被隔离，并记录在可撤销事务中。",
"recoveryCenter.rebuildQuarantineHint": "现有文件只会重命名，不会删除。",
"recoveryCenter.evidenceDetails": "技术证据",
"recoveryCenter.binariesTitle": "发布组件",
"recoveryCenter.sessionsTitle": "会话存储",
"recoveryCenter.configTitle": "配置检查",
"recoveryCenter.ok": "正常",
"recoveryCenter.unavailable": "不可用",
"recoveryCenter.files": "{count} 个文件",
"recoveryCenter.missing": "缺失",
"recoveryCenter.invalid": "无效",
"recoveryCenter.generatedAt": "证据生成时间：{time}",
"recoveryCenter.actionChanged": "恢复操作已完成，证据已刷新。",
"recoveryCenter.actionNoChange": "操作已完成，没有匹配状态需要改动。",
"recoveryCenter.finding.startupStateInvalid": "启动账本不可读",
"recoveryCenter.finding.crashLoop": "连续未完成启动",
"recoveryCenter.finding.configInvalid": "配置无效",
"recoveryCenter.finding.snapshotsUnreadable": "配置快照不可读",
"recoveryCenter.finding.repairMetadataInvalid": "修复事务元数据无效",
"recoveryCenter.finding.updateProbationary": "已安装更新仍在观察期",
"recoveryCenter.finding.updateMetadataInvalid": "更新事务元数据无效",
"recoveryCenter.finding.pluginsInvalid": "插件状态不可读",
"recoveryCenter.open": "打开恢复中心",
"recoveryCenter.banner": "恢复证据需要关注。",
};

const zhTWRecovery: RecoveryDictionary = {
"recoveryCenter.eyebrow": "離線復原",
"recoveryCenter.title": "復原中心",
"recoveryCenter.safeModeBody": "安全模式已啟用。目前只提供不讀取憑據的復原控制；模型、工具、外掛、Hook 和舊工作階段均未載入。",
"recoveryCenter.crashLoopBody": "偵測到連續未完成啟動。返回正常啟動前，請先核對復原證據。",
"recoveryCenter.healthyBody": "目前沒有需要處理的復原問題。在你明確選擇操作前，下方證據均為唯讀。",
"recoveryCenter.attentionBody": "復原證據需要關注。請核對問題，只執行與實際故障相符的操作。",
"recoveryCenter.refresh": "重新整理",
"recoveryCenter.close": "返回工作區",
"recoveryCenter.credentialFree": "此介面不會載入 API 金鑰、使用者設定、模型服務商、MCP、外掛、Hook 或 Agent 執行階段。",
"recoveryCenter.loading": "正在檢查復原證據…",
"recoveryCenter.statusOverview": "復原狀態概覽",
"recoveryCenter.startup": "啟動帳本",
"recoveryCenter.configuration": "設定",
"recoveryCenter.releaseUnit": "已安裝版本",
"recoveryCenter.extensions": "擴充",
"recoveryCenter.notRecorded": "尚未記錄",
"recoveryCenter.failures": "限定視窗內有 {count} 次未完成啟動",
"recoveryCenter.configValid": "{total} 項檢查中 {valid} 項安全",
"recoveryCenter.snapshots": "{count} 份已驗證快照",
"recoveryCenter.noSnapshots": "沒有已驗證快照",
"recoveryCenter.updatePending": "{version} 仍在觀察期",
"recoveryCenter.noPendingUpdate": "沒有待確認更新",
"recoveryCenter.binaries": "已檢查 {count} 個發布元件",
"recoveryCenter.noBinaryEvidence": "沒有已安裝二進位證據",
"recoveryCenter.pluginsEnabled": "已啟用 {count} 個外掛",
"recoveryCenter.pluginsDisabled": "已停用 {count} 個外掛",
"recoveryCenter.storeUnreadable": "狀態儲存不可讀",
"recoveryCenter.findings": "發現的問題",
"recoveryCenter.findingsHint": "證據按嚴重程度排序，不會自行觸發任何變更。",
"recoveryCenter.noFindings": "沒有復原問題",
"recoveryCenter.actions": "復原操作",
"recoveryCenter.actionsHint": "每項操作都需要明確確認、範圍受限、執行前複核身分，並在完成後重新檢查。",
"recoveryCenter.repairConfig": "隔離無效設定",
"recoveryCenter.repairConfigBody": "只移走所選的無效 TOML；若存在已驗證快照，全域設定會自動復原最新一份。",
"recoveryCenter.repairGlobal": "修復全域設定",
"recoveryCenter.repairProject": "修復專案設定",
"recoveryCenter.repair": "修復",
"recoveryCenter.rollbackUpdate": "回復已安裝版本",
"recoveryCenter.rollbackUpdateBody": "只有目前交易身分和所有備份雜湊仍完全相符時，才復原完整的上一發布單元。",
"recoveryCenter.rollback": "回復",
"recoveryCenter.restoreSnapshot": "復原設定快照",
"recoveryCenter.restoreSnapshotBody": "用一份已驗證快照取代全域設定，並保留可復原交易。",
"recoveryCenter.snapshot": "已驗證快照",
"recoveryCenter.restore": "復原",
"recoveryCenter.undoRepair": "復原上次修復",
"recoveryCenter.undoRepairBody": "只復原目前報告中顯示的精確復原交易。",
"recoveryCenter.undo": "復原",
"recoveryCenter.disablePlugins": "停用全部外掛",
"recoveryCenter.disablePluginsBody": "停止擴充執行，但不刪除已安裝套件，也不讀取其憑據。",
"recoveryCenter.disable": "停用外掛",
"recoveryCenter.pluginsCanReenable": "外掛套件仍會保留，完成審查後可再次啟用。",
"recoveryCenter.rebuildState": "重建桌面狀態",
"recoveryCenter.rebuildStateBody": "隔離分頁、專案、視窗或縮放等派生狀態，由 Desktop 根據規範資料重建。",
"recoveryCenter.rebuildTarget": "派生狀態",
"recoveryCenter.rebuildAll": "全部派生狀態",
"recoveryCenter.rebuildTabs": "分頁",
"recoveryCenter.rebuildProjects": "專案",
"recoveryCenter.rebuildWindow": "視窗位置",
"recoveryCenter.rebuildZoom": "縮放",
"recoveryCenter.rebuild": "重建",
"recoveryCenter.working": "執行中…",
"recoveryCenter.confirmRepairTitle": "修復設定？",
"recoveryCenter.confirmRepairGlobal": "隔離無效全域設定，並在可用時復原已驗證快照？",
"recoveryCenter.confirmRepairProject": "隔離目前工作區的無效專案設定？",
"recoveryCenter.confirmRollbackTitle": "回復此版本？",
"recoveryCenter.confirmRollback": "復原安裝 {version} 之前的完整發布單元？",
"recoveryCenter.confirmRestoreTitle": "復原此快照？",
"recoveryCenter.confirmRestore": "用所選已驗證快照取代全域設定？",
"recoveryCenter.confirmUndoTitle": "復原上次修復？",
"recoveryCenter.confirmUndo": "復原到目前顯示的修復交易執行前狀態？",
"recoveryCenter.confirmDisableTitle": "停用全部外掛？",
"recoveryCenter.confirmDisable": "在下次正常啟動前停用所有目前已啟用的外掛？",
"recoveryCenter.confirmRebuildTitle": "重建桌面狀態？",
"recoveryCenter.confirmRebuild": "隔離所選派生狀態並讓 Desktop 重新建立？",
"recoveryCenter.reversibleHint": "原檔案會被隔離，並記錄在可復原交易中。",
"recoveryCenter.rebuildQuarantineHint": "現有檔案只會重新命名，不會刪除。",
"recoveryCenter.evidenceDetails": "技術證據",
"recoveryCenter.binariesTitle": "發布元件",
"recoveryCenter.sessionsTitle": "工作階段儲存",
"recoveryCenter.configTitle": "設定檢查",
"recoveryCenter.ok": "正常",
"recoveryCenter.unavailable": "無法使用",
"recoveryCenter.files": "{count} 個檔案",
"recoveryCenter.missing": "缺少",
"recoveryCenter.invalid": "無效",
"recoveryCenter.generatedAt": "證據產生時間：{time}",
"recoveryCenter.actionChanged": "復原操作已完成，證據已重新整理。",
"recoveryCenter.actionNoChange": "操作已完成，沒有符合的狀態需要變更。",
"recoveryCenter.finding.startupStateInvalid": "啟動帳本不可讀",
"recoveryCenter.finding.crashLoop": "連續未完成啟動",
"recoveryCenter.finding.configInvalid": "設定無效",
"recoveryCenter.finding.snapshotsUnreadable": "設定快照不可讀",
"recoveryCenter.finding.repairMetadataInvalid": "修復交易中繼資料無效",
"recoveryCenter.finding.updateProbationary": "已安裝更新仍在觀察期",
"recoveryCenter.finding.updateMetadataInvalid": "更新交易中繼資料無效",
"recoveryCenter.finding.pluginsInvalid": "外掛狀態不可讀",
"recoveryCenter.open": "開啟復原中心",
"recoveryCenter.banner": "復原證據需要關注。",
};

const recoveryDictionaries: Record<Locale, RecoveryDictionary> = {
  en: enRecovery,
  zh: zhRecovery,
  "zh-TW": zhTWRecovery,
};

export type RecoveryTranslator = (key: RecoveryKey, vars?: Record<string, string | number>) => string;

export function useRecoveryT(): RecoveryTranslator {
  const { locale } = useI18n();
  return (key, vars) => {
    const value = recoveryDictionaries[locale][key] ?? enRecovery[key] ?? key;
    if (!vars) return value;
    return value.replace(/\{(\w+)\}/g, (_, name: string) => vars[name] !== undefined ? String(vars[name]) : "{" + name + "}");
  };
}
